### ISSUE TITLE
Live bot

### ISSUE THREAD

**Issue by RonnieBlaze** [bchanudet/OctoPrint-Octorant#13]
how hard would it be to add the ability for this to be a live bot also? one that could respond to commands ?

**Comment by bchanudet** [comment]
Hello and thanks for stopping by.

Your question is actually the same than on #6, and you'll find there my answer about this request. To summarize briefly, I'm considering commands to be out-of-scope for this plugin, so I won't add them here. But if anyone want to collaborate I will be glad to offer my help on this.
