### ISSUE TITLE
Double Complete Notification

### ISSUE THREAD

**Issue by tdub415** [bchanudet/OctoPrint-Octorant#22]
Octorant is currently notifying me twice upon print completion, one for 100% and one for complete.  Initially it was (or at least seemed to be) supressing the 100% message in lieu of the the Complete message.

**Comment by bchanudet** [comment]
Sorry for the delay in treating your feedback.

I got a print into completion today and was able to confirm the bug. Fixing it will be a little tricky, as I already encountered in the past OctoPrint "miscalulating" the percentage and 100% was not "completed", and it even got up to "110%".
