### ISSUE TITLE
ERROR: octoprint-octorant 1.2.2 has requirement Pillow==5.0.0, but you'll have pillow 7.0.0 which is incompatible.

### ISSUE THREAD

**Issue by halkeye** [bchanudet/OctoPrint-Octorant#39]
Is there a reason pillow is pinned to 5.0.0?

Docker python 2.7 gives

ERROR: octoprint-octorant 1.2.2 has requirement Pillow==5.0.0, but you'll have pillow 6.2.2 which is incompatible.

Seems to still install

**Comment by bchanudet** [comment]
Hello and thanks for your report.

As a matter of fact I usually pin the version of packages I use on projects on very low maintenance mode. This is a way for me to avoid having to bother also with packages updates too regularly. Not the best thing to do I know, but I gotta keep sane. :)

Nevertheless I tested with the last version of Pillow available on Python 3, that seems to be Pillow 7.2.2, and everything works as expected. So I unpinned the version of Pillow, while keeping 5.0.0 as the minimum required.

This will be available in the upcoming version, 1.2.3. :)
