### ISSUE TITLE
remaining_formatted

### ISSUE THREAD

**Issue by qkdefus** [bchanudet/OctoPrint-Octorant#42]
remaining_formatted does not work as intended on "printing process : started"
for some reason i randomly get "The variable {remaining_formatted} is invalid for this message"
and some prints it return the correct value when starting a new print.

if possible i would love {progress} to work on "printing process : started" as well,
even tho value is zero :)

thanks

**Comment by rwaight** [comment]
What would need to be added for `{remaining_formatted}` to be added to the _started event_ printing process?  I saw that `{remaining_formatted}` is not listed as an option for the _started event_ printing process and validated with the following:

> I've started printing `{name}`, the print will take approximately {remaining_formatted}.
>   **Octorant Warning**
> The variable `{remaining_formatted}` is invalid for this message
> Available variables: `{origin}`, `{name}`, `{spent}`, `{user}`, `{owner}`, `{path}`, `{spent_formatted}`, `{size}`
