### ISSUE TITLE
@mentions not working?

### ISSUE THREAD

**Issue by PitbullRaven** [bchanudet/OctoPrint-Octorant#43]
Hi. I have tried getting Octorant to use @mentions, without success. 

For instance, for the printer error state, in the Octorant settings, I have:
⚠️ @MyHandle  Your printer is in an erroneous state.

This results in that text showing in the stream, but the handle is not highlighted and does not trigger the ping.

I have also tried @MyHandle#6809 which would be my user according to Discord, yet still nothing.

Any insight?

**Comment by ragnork2** [comment]
There's something about discord that doesn't let mentions work without specific functions in the code, this makes things like sudo commands not able to work with mentions.

**Comment by KipLandwehr** [comment]
I have tags working with my Octorant setup. The trick is that you have to use your unique ID. The format is
`<@!#################>`. You can get yours by typing `\@yourhandle#6809` into a discord channel.

**Comment by PitbullRaven** [comment]
> I have tags working with my Octorant setup. The trick is that you have to use your unique ID. The format is `<@!#################>`. You can get yours by typing `\@yourhandle#6809` into a discord channel.

Thanks for the tip. I'll give it a go.
