### ISSUE TITLE
Offer to send the GCODE thumbnail along the message

### ISSUE THREAD

**Issue by mavermc** [bchanudet/OctoPrint-Octorant#47]
Pull and post the PrusaSlic3r image that's embedded in the gcode, this plugin is able to pull and display them: https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails

It be cool if the initial discord message that it started printed would include this preview of what's going to be printed

**Comment by bchanudet** [comment]
Hello!

That indeed seems like a useful thing to have when starting the print (more useful than a snapshot of an empty bed atleast), I'll have a look at what I can do there. :)
