### ISSUE TITLE
Upload to SD Printing Process Bug

### ISSUE THREAD

**Issue by SalmonSays** [bchanudet/OctoPrint-Octorant#58]
I have just recently started uploading files to my SD card through Octoprint after noticing much better print quality using this method, and a quirk appeared in OctoRant on the latest version of OctoPrint as of time of writing- the Upload to SD prompt uses the same percentage progress bar as a normal print process, and it sends Printing Progress messages out with screenshots even though no print is in progress. Instead screenshots/messages are posted at SD card file upload intervals matching the "notify every xx%" print progress interval.

**Comment by omnislash772** [comment]
Confirming that I am also getting this issue
![image](https://user-images.githubusercontent.com/1793719/190912294-6764c1bd-04b1-4e44-9d99-c6c3807d2c2c.png)

**Comment by omnislash772** [comment]
Should be as easy as suppressing any updates if octoprint's state is "Sending file to SD"
