### ISSUE TITLE
Tiny thumbnails?

### ISSUE THREAD

**Issue by mavermc** [bchanudet/OctoPrint-Octorant#65]
I use Prusa Slicer and it gets thumbnails but it super tiny
![image](https://github.com/bchanudet/OctoPrint-Octorant/assets/21307215/a99bec91-6a35-4dcf-80ae-bce5903fba79)

**Comment by bchanudet** [comment]
Hello,

Thanks for you feedback. What are your settings in PrusaSlicer regarding thumbnails?
