### ISSUE TITLE
Not sendindg messages after reinstall

### ISSUE THREAD

**Issue by LukasBlk** [bchanudet/OctoPrint-Octorant#68]
Hi, I'm having a problem with Discord notifications. 

I had Octorant installed on my Octoprint RPi server for almost 2 years and it was connected to my Ender 3 Pro, Octorant was sending all the messages to my Discord server. There was no issue at all. After 2 years I bought a new Ender S1 Pro and decided to reinstall Octoprint so that each printer has its own instance of Octoprint. I used this script (https://github.com/paukstelis/octoprint_deploy). 

Anyway, after installing and setting up both printers and installing Octorant on each instance of Octoprint, I'm now experiencing this issue. Neither of the printers is sending messages to my discord server about starting, pausing, or finishing print. Even for the Ender 3 Pro which worked 2 years before, I did not change the firmware, the only new thing is a new version of Octoprint and Octorant.  I receive only Octoprint online message and Printer ready message, after that, no other info about printing, pausing, and finishing prints is not sent to Discord. 

Both of the printers are now showing this message in OctoPrint ("Your printer's firmware supports host action commands, but they are disabled."), but before the installation process, the Ender 3 was totally working. 

I googled several days but not found anyone else having the same issue, Can you please help me? If you need some log files for the printers, I will add them according to your instructions. 

![image](https://github.com/bchanudet/OctoPrint-Octorant/assets/131153420/10b874e0-a7b4-45a9-b00e-31c1bb8026cd)
![image](https://github.com/bchanudet/OctoPrint-Octorant/assets/131153420/78ca1e34-d2c0-4fce-a7a9-e448ef9d7b0a)

![image](https://github.com/bchanudet/OctoPrint-Octorant/assets/131153420/b3e0d2fd-1b3d-4927-be6f-3ba443b8a1a3)

**Comment by bchanudet** [comment]
Hi,

Could you maybe provide your server logs? Usually there is at least one Octorant line for each message that should be sent, so we should be able to see what happened.

If you don't want to attach them here for privacy reasons, you can also send them direct to me to dev@benjaminchanudet.com

**Comment by LukasBlk** [comment]
Hi,

thank you for your message. Can you help me a little bit about what log you need? I don't have many programming skills. I'm running OctoPrint with Octorant on Raspberry Pi and OctoPi OS.

**Comment by bchanudet** [comment]
Don't worry, that doesn't need programing skills. :)

Open OctoPrint settings. Under the "OctoPrint" section, you should find a page for "Logging". In there, you'll see a list of log files. The one simply named "octoprint.log" is the one I'm interested in.

Download the file, then when answering to the thread here, you will be able to drag & drop the file into the message to attach it automatically.

**Comment by LukasBlk** [comment]
Thank you for the instructions, here is the LOG file from the instance with Ender S1 Pro connected.

[S1PRO_octoprint.log](https://github.com/bchanudet/OctoPrint-Octorant/files/11643380/S1PRO_octoprint.log)

**Comment by bchanudet** [comment]
Many thanks for the logs. 

From what I'm seeing you are affected by a bug that I also encountered myself last week, and that should already be fixed by cd268fe877010bbae77d0903166ebd9d5f951554

I'm hopeful to have a new version to release this weekend or beginning next week. Once done I'll probably message you here to confirm that this fixes your bug. :)

**Comment by LukasBlk** [comment]
Thank you for the diagnostic and help :) I will test my setup once you release the new version and give feedback.

**Comment by bchanudet** [comment]
I just released the v1.3.2 of the plugin, feel free to test it and report back to me if this fixed your bug. :)

**Comment by LukasBlk** [comment]
Hi,

I finally updated your plugin and it seems nothing has changed. I
uninstalled it, restarted the Raspberry, and installed the new plugin
again. Still no info messages about printing, just starting of octoprint
and printer ready :(

[image: image.png]
[image: image.png]

po 5. 6. 2023 v 23:07 odesílatel Benjamin Chanudet ***@***.***>
napsal:

**Comment by bchanudet** [comment]
Hi,

Sorry for this. 

Same as the previous time, could you maybe provide some logs that would help me diagnose this case?

Many thanks :)

**Comment by LukasBlk** [comment]
Hi,

sure thing, here's the current log file :)

[image: image.png]

ne 2. 7. 2023 v 20:20 odesílatel Benjamin Chanudet ***@***.***>
napsal:

**Comment by bchanudet** [comment]
Sadly, replies by email don't support attachments, so I see nothing in your last reply.

**Comment by LukasBlk** [comment]
Uploading log via GitHub again :)

![image](https://github.com/bchanudet/OctoPrint-Octorant/assets/131153420/fc392295-5ddf-413a-bcb7-d0b322c31b9a)

[octoprint.log](https://github.com/bchanudet/OctoPrint-Octorant/files/11954787/octoprint.log)

**Comment by bchanudet** [comment]
Hello,

@LukasBlk, I don't see in your log any prints running, therefore I can't see what errors OctoRant triggers (but I can confirm it loads correctly during OctoPrint startup. Can you try printing a small object to see if we can detect errors. 

@Wackeljupp, same thing, could you provide your octoprint logs? (best would be those generated during a print)

Also to you both, can you give me your OctoPrint version, and how it's installed? (via OctoPi, OctoPi with the new camera stack, or by manual installation?)

**Comment by Wackeljupp** [comment]
Sorry for late reply.
Here is my log from a print.
I can't really tell how i installed it. 
[octoprint (3).log](https://github.com/bchanudet/OctoPrint-Octorant/files/12060407/octoprint.3.log)

**Comment by LukasBlk** [comment]
I also apologize for the late reply, here's my log file. I'm running OctoPrint version 1.9.0, Python 3.9.2 and I installed it via Raspberry Pi Imager, I selected the OctoPi installation which includes OctoPrint.
[octoprint.log](https://github.com/bchanudet/OctoPrint-Octorant/files/12063812/octoprint.log)

**Comment by Wackeljupp** [comment]
B/c of another problem i reinstalled everything now.
and now it works properly
