### ISSUE TITLE
Webcam image is reversed

### ISSUE THREAD

**Issue by waumand** [bchanudet/OctoPrint-Octorant#7]
Hi,
your plugin is really cool (maybe one of the best Octoprint plugin I used !), but sadly it didn't keep the reversal statut of your webcam.
My camera (official from Raspberry Pi) is verticaly reversed and it's fine with Octoprint but not right with your notification picture in discord as you can see with my picture.

![capture d ecran 2018-03-12 a 18 58 10](https://user-images.githubusercontent.com/6934787/37301324-8e09793e-2628-11e8-8f7f-863c95f97c86.png)
Can you fix it ? Thank's a lot !

**Comment by bchanudet** [comment]
I figured out this is not a real duplicate, as #8 is actually the newest of the two bugs, but to make it easier I'll update the progress there. Your comment is duly noted though, thanks for your feedback!

**Comment by bchanudet** [comment]
As said in #8, I just release [version 1.1.0](https://github.com/bchanudet/OctoPrint-Octorant/releases/tag/1.1.0) that gives the plugin the access to these new parameters so it can send the snapshot in the expected orientation.
