### ISSUE TITLE
Also allow Cura thumbnails

### ISSUE THREAD

**Issue by BobSleeuw** [bchanudet/OctoPrint-Octorant#75]
Is it possible to also allow .ufp thumbnail files for gcode sliced in Cura? Other plugins like Slicer Thumbnails will show the Cura thumbnails, but that still doesn't make it possible to use them in this plugin.

**Comment by bchanudet** [comment]
Hello,

I'm not familiar with Cura's thumbnails. Are they generated aside the gcode or inside like PrusaSlicer? 

Is there a way for you to send me a sample here on this issue? Many thanks :)

**Comment by BobSleeuw** [comment]
They are generated in the gcode, as commented lines at the start (I believe with base64 encoding). They are denoted at the start by `; thumbnail begin width height <variable I don't know>` and end at `; thumbnail end`. 

Here is a sample .gcode file of a small cube (I changed the extension to .txt since github doesn't support .gcode)

[5mmCube.txt](https://github.com/bchanudet/OctoPrint-Octorant/files/13111418/5mmCube.txt)

**Comment by bchanudet** [comment]
Thanks for the sample gcode!

That seems awfully close to the format I already handle for PrusaSlicer's thumbnails, I'll have a look at what's different between the two and check. :)

**Comment by BobSleeuw** [comment]
Awesome, thanks!

**Comment by BobSleeuw** [comment]
Works like a charm, awesome! Thanks for the quick fix @bchanudet!
