### ISSUE TITLE
Add disable

### ISSUE THREAD

**Issue by nangad** [bchanudet/OctoPrint-Octorant#9]
Can you add a disable feature in the config?

**Comment by bchanudet** [comment]
Hello and thanks to you for stopping by!

Could you expand a bit more on what you are waiting here? There is already a "global disable" feature, in the **Plugin Manager** settings tab. 
![plugin_manager](https://user-images.githubusercontent.com/5636773/37431117-9ccf2f24-27d4-11e8-9b60-7857a736e855.jpg)

But if I'm missing something feel free to tell me, maybe I can help :)

**Comment by bchanudet** [comment]
Hello, 

As there was no answer to this issue, I'm closing it. Feel free to reopen it if necessary.

Cheers.
